final: prev: {
  deno2nix = {
    # Import a deps.nix file generated by deno2nix CLI
    # Returns { sources, cache } where cache is ready-to-use npm cache
    # Usage: deno2nix.importDeps ./deps.nix
    importDeps = depsFile: final.callPackage depsFile {};
  };
}
