# This file has been generated by deno2nix. Do not edit!

{ stdenv, fetchurl, lib }:

let
  sources = {
    "@hono/zod-validator-0.4.3" = {
      type = "npm";
      name = "_at_hono_slash_zod-validator";
      packageName = "@hono/zod-validator";
      version = "0.4.3";
      registryPath = "registry.npmjs.org/@hono/zod-validator/0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hono/zod-validator/-/zod-validator-0.4.3.tgz";
        sha512 = "xIgMYXDyJ4Hj6ekm9T9Y27s080Nl9NXHcJkOvkXPhubOLj8hZkOL8pDnnXfvCf5xEE8Q4oMFenQUZZREUY2gqQ==";
      };
    };
    "hono-4.11.3" = {
      type = "npm";
      name = "hono";
      packageName = "hono";
      version = "4.11.3";
      registryPath = "registry.npmjs.org/hono/4.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hono/-/hono-4.11.3.tgz";
        sha512 = "PmQi306+M/ct/m5s66Hrg+adPnkD5jiO6IjA7WhWw0gSBSo1EcRegwuI1deZ+wd5pzCGynCcn2DprnE4/yEV4w==";
      };
    };
    "zod-3.25.76" = {
      type = "npm";
      name = "zod";
      packageName = "zod";
      version = "3.25.76";
      registryPath = "registry.npmjs.org/zod/3.25.76";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
        sha512 = "gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
      };
    };
  };

  # Build the npm cache directory for Deno
  cache = stdenv.mkDerivation {
    name = "deno-npm-cache";
    dontUnpack = true;
    buildPhase = ''
      mkdir -p $out
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg:
        lib.optionalString (pkg.registryPath != "") ''
          mkdir -p "$out/${pkg.registryPath}"
          tar -xzf ${pkg.src} -C "$out/${pkg.registryPath}" --strip-components=1
        ''
      ) sources)}
    '';
    installPhase = "true";
  };

in {
  inherit sources cache;
}
