# This file has been generated by deno2nix. Do not edit!

{ stdenv, fetchurl, lib }:

let
  sources = {
    "hono-4.11.3" = {
      type = "npm";
      name = "hono";
      packageName = "hono";
      version = "4.11.3";
      registryPath = "registry.npmjs.org/hono/4.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hono/-/hono-4.11.3.tgz";
        sha512 = "PmQi306+M/ct/m5s66Hrg+adPnkD5jiO6IjA7WhWw0gSBSo1EcRegwuI1deZ+wd5pzCGynCcn2DprnE4/yEV4w==";
      };
    };
  };

  # Build the npm cache directory for Deno
  cache = stdenv.mkDerivation {
    name = "deno-npm-cache";
    dontUnpack = true;
    buildPhase = ''
      mkdir -p $out
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg:
        lib.optionalString (pkg.registryPath != "") ''
          mkdir -p "$out/${pkg.registryPath}"
          tar -xzf ${pkg.src} -C "$out/${pkg.registryPath}" --strip-components=1
        ''
      ) sources)}
    '';
    installPhase = "true";
  };

in {
  inherit sources cache;
}
